image: maven:latest

before_script:
  - bash eval.sh
  - mkdir run && cp -r run-template/1.15.1 run && cp -r run-template/1.15.1/Labyfy versioned/labyfy-1.15.1 && ls -la versioned/labyfy-1.15.1
  - cd versioned/labyfy-1.15.1 && sh ../../gradlew :versioned:labyfy-1.15.1:download-libraries && cd ../..

test:
  stage: test
  script:
  - sh gradlew test

deploy:
  stage: deploy
  script:
  - sh gradlew artifactoryPublish
  environment:
    name: production
  only:
  - master
  - 35-fix-jar-creation