build:
  stage: build
  script:
  - bash eval.sh # script to workaround backslash excludes
  - mkdir run
  - cp -r run-template/1.15.1 run
  - cp -r run-template/1.15.1/Labyfy versioned/labyfy-1.15.1
# - sh gradlew download-libraries
  - sh gradlew build
  
deploy:
  stage: deploy
  only:
    - master
  script: 
    - docker pull getsentry/sentry-cli
    - docker run --rm -v $(pwd):/work getsentry/sentry-cli --auth-token ${SENTRY_AUTH_TOKEN} --url ${SENTRY_URL} releases -o sentry new -p labyfy $CI_PIPELINE_ID