stages:
  - version
  - build
  - test
  - deploy
  - publish
  - replay

variables:
  SCRIPTS_REPO: "git@git.labymod.net:client/labymod4/common-scripts.git"

before_script:
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - ssh-keyscan git.labymod.net >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "$SCRIPTS_REPO" "$SCRIPTS_DIR"
  - bash $SCRIPTS_DIR/genSemVer.sh build ${CI_JOB_ID} > .dev-version

version:
  stage: version
  script:
    - bash $SCRIPTS_DIR/versionPreCheck.sh "${CI_COMMIT_MESSAGE}"
    - bash $SCRIPTS_DIR/genSemVer.sh $(cat BUMP_TYPE) > .dev-version
    - export TAG=$(cat .dev-version)
    - git config --global user.email "gitlab-ci@gitlab.labymod.net"
    - git config --global user.name "gitlab-ci"
    - git remote set-url --push origin "git@git.labymod.net:client/labymod4/Labyfy.git"
    - git tag -a ${TAG} -m "${CI_COMMIT_MESSAGE}"
    - git push origin ${TAG}
  artifacts:
    paths:
      - .dev-version
  only:
    - master

build:
  stage: build
  script:
    - sh $SCRIPTS_DIR/eval.sh
    - sh $SCRIPTS_DIR/eval.sh "./labyfy-gradle-plugin/"
    - mkdir run && cp -r run-template/1.15.1 run && cp -r run-template/1.15.1/Labyfy versioned/labyfy-1.15.1 && ls -la versioned/labyfy-1.15.1
    - sh gradlew -Ppublish_token=$PUBLISH_TOKEN build --stacktrace --refresh-dependencies
  artifacts:
    name: $(cat .dev-version)
    paths:
      - build/libs
  only:
    - branches
  retry: 2
  except:
    - master

deploy_to_artifactory:
  stage: deploy
  script:
    - sh $SCRIPTS_DIR/eval.sh
    - sh $SCRIPTS_DIR/eval.sh "./labyfy-gradle-plugin/"
    - mkdir run && cp -r run-template/1.15.1 run && cp -r run-template/1.15.1/Labyfy versioned/labyfy-1.15.1 && ls -la versioned/labyfy-1.15.1
    - bash $SCRIPTS_DIR/branchingPreCheck.sh
    - bash $SCRIPTS_DIR/genSemVer.sh prerel SNAPSHOT > .dev-version || exit 1
    - cat .dev-version
    - sh gradlew artifactoryPublish
  environment:
    name: development
  only:
    - develop
  when: on_success
  retry: 2

publish_version:
  stage: publish
  script:
    - sh $SCRIPTS_DIR/eval.sh
    - sh $SCRIPTS_DIR/eval.sh "./labyfy-gradle-plugin/"
    - mkdir run && cp -r run-template/1.15.1 run && cp -r run-template/1.15.1/Labyfy versioned/labyfy-1.15.1 && ls -la versioned/labyfy-1.15.1
    - bash $SCRIPTS_DIR/branchingPreCheck.sh
    - bash $SCRIPTS_DIR/genSemVer.sh release > .dev-version || exit 1
    - cat version
    - sh gradlew artifactoryPublish
    - export MD5SUM=$(md5sum build/libs/Labyfy-$(cat version).jar | cut -f1 -d' ')
    - sed -i "s/\"md5\".*/\"md5\":\ \"${MD5SUM})\"/1" manifest.json
    - sed -i "s/VERSION/$(cat version)/g" manifest.json
    - cat manifest.json
    - export FILE="labyfy-$(cat version).jar"
    - mv build/libs/$FILE .
    - curl -H "Authorization:Bearer ${DISTRIBUTOR_TOKEN}" -F "file=@$FILE" http://dist.laby.tech:8080/publish/Labyfy/$(cat version)
    - curl -H "Authorization:Bearer ${DISTRIBUTOR_TOKEN}" -F 'file=@manifest.json' http://dist.laby.tech:8080/publish/Labyfy/$(cat version)
    - bash $SCRIPTS_DIR/releaseVersionToGit.sh ${CI_PROJECT_ID} ${CI_JOB_TOKEN} $(cat version) $(cat version) ${CI_COMMIT_MESSAGE}
  environment:
    name: production
  only:
    - tags
  when: on_success

update_develop_version:
  stage: replay
  script:
    - git checkout origin/develop
    - git pull origin master
    - bash $SCRIPTS_DIR/genSemVer.sh release > .dev-version || exit 1
    - export VERSION=$(cat .dev-version)
    - rm -r semver-tool
    - rm version
    - git commit -a -m "${VERSION}"
    - git config --global push.default simple
    - git push origin HEAD:develop
  only:
    - tags
  when: on_success