stages:
  - version
  - build
  - test
  - deploy

variables:
  SCRIPTS_REPO: "git@git.labymod.net:client/labymod4/common-scripts.git"

before_script:
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - ssh-keyscan git.labymod.net >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "$SCRIPTS_REPO" "$SCRIPTS_DIR"
  - sh $SCRIPTS_DIR/eval.sh
  - sh $SCRIPTS_DIR/eval.sh "./library-downloader/"
  - mkdir run && cp -r run-template/1.15.1 run && cp -r run-template/1.15.1/Labyfy versioned/labyfy-1.15.1 && ls -la versioned/labyfy-1.15.1
  - cd versioned/labyfy-1.15.1 && sh ../../gradlew :versioned:labyfy-1.15.1:download-libraries --refresh-dependencies && cd ../..
  - bash $SCRIPTS_DIR/genSemVer.sh build ${CI_BUILD_NAME}.${CI_BUILD_REF_NAME} > version
  - sed -i "s/version .*/version '$(cat version)'/1" build.gradle

version:
  stage: version
  script:
    - bash $SCRIPTS_DIR/genSemVer.sh patch > version
    - export TAG=$(cat version)
    - git config --global user.email "gitlab-ci@gitlab.labymod.net"
    - git config --global user.name "gitlab-ci"
    - git remote set-url --push origin "git@git.labymod.net:client/labymod4/Labyfy.git"
    - git tag -a ${TAG} -m "${CI_COMMIT_MESSAGE}"
    - git push origin ${TAG}
  artifacts:
    paths:
      - version
  only:
    - master

build:
  stage: build
  script:
    - sh gradlew build --refresh-dependencies
  artifacts:
    name: $(cat version)
    paths:
      - build/libs
  only:
    - branches

test:
  stage: test
  script:
    - sh gradlew test
  when: on_success

deploy:
  stage: deploy
  script:
    - sh gradlew artifactoryDeploy
  environment:
    name: development
  only:
    - develop
  when: on_success

publish:
  stage: deploy
  script:
    - sh gradlew artifactoryPublish
  environment:
    name: production
  only:
    - tags
  when: on_success
